import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
const html = readFileSync(new URL("./index.html", import.meta.url), "utf8");
assert.ok(html.includes('id="projetosPage"'));
assert.ok(html.includes('id="projectForm"'));
assert.ok(html.includes('id="projectList"'));
assert.ok(html.includes("ruan.alpha.projects.v1"));
assert.ok(html.includes("data:{tasks,entries,notes,projects,routines}"));
assert.ok(html.includes("payload.data.projects!==undefined"));
assert.ok(html.includes("payload.data.routines!==undefined"));
assert.ok(html.includes("KEYS.projects,next.projects"));
assert.ok(html.includes("KEYS.routines,next.routines"));
assert.ok(html.includes("privacyProjects"));
assert.ok(html.includes("ALFA 0.4"));
console.log("Ruan projects tests passed.");

assert.ok(html.includes('id="rotinasPage"'));
assert.ok(html.includes('id="routineForm"'));
assert.ok(html.includes('id="routineList"'));
assert.ok(html.includes("ruan.alpha.routines.v1"));
assert.ok(html.includes("data:{tasks,entries,notes,projects,routines}"));
assert.ok(html.includes("payload.data.routines!==undefined"));
assert.ok(html.includes("KEYS.routines,next.routines"));
assert.ok(html.includes("homeRoutineDone"));
assert.ok(html.includes("routineStreakCount"));
console.log("Ruan routines tests passed.");
