import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
const html = readFileSync(new URL("./index.html", import.meta.url), "utf8");
assert.ok(html.includes('id="projetosPage"'));
assert.ok(html.includes('id="projectForm"'));
assert.ok(html.includes('id="projectList"'));
assert.ok(html.includes("ruan.alpha.projects.v1"));
assert.ok(html.includes("data:{tasks,entries,notes,projects}"));
assert.ok(html.includes("payload.data.projects!==undefined"));
assert.ok(html.includes("KEYS.projects,next.projects"));
assert.ok(html.includes("privacyProjects"));
assert.ok(html.includes("ALFA 0.3"));
console.log("Ruan projects tests passed.");
