import { id } from "./id.js";
export class CommunicationBus {
  constructor({road,registry=null,contractRegistry=null}={}){if(!road)throw new Error("ROAD_REQUIRED");this.road=road;this.registry=registry;this.contractRegistry=contractRegistry;this.messages=[];this.receipts=[];this.pending=new Map();}
  send(operation){const route=this.road.route(operation);if(!route.success)return route;const contractId=`EXCHANGE:${operation.origin}:${route.capability.owner}`;
    if(!operation.destination)operation.destination=route.capability.owner;
    if(this.contractRegistry&&!this.contractRegistry.get(contractId))this.contractRegistry.register({id:contractId,origin:operation.origin,destination:route.capability.owner,operations:[operation.type],capability:route.capability.id,reversible:true,metadata:{generated:true,route:route.delivery.id}});
    const contract=this.contractRegistry?.validate?.(operation,{contractId});
    if(contract&&!contract.valid)return{success:false,reason:"MODULE_CONTRACT_INVALID",contract};
    operation.context={...(operation.context||{}),contractId};
    const message={id:id("MSG"),operationId:operation.id,type:"OPERATION_REQUEST",origin:operation.origin,destination:route.capability.owner,service:operation.service,payload:structuredClone(operation.payload),routeId:route.delivery.id,at:new Date().toISOString()};const receipt={id:id("REC"),messageId:message.id,operationId:operation.id,senderId:operation.origin,receiverId:route.capability.owner,routeId:route.delivery.id,status:"RECEIVED",at:new Date().toISOString()};this.messages.push(message);this.receipts.push(receipt);this.pending.set(operation.id,{message,receipt});this.registry?.recordEvent?.(operation,"MESSAGE_SENT",{message,receipt});return{success:true,status:"DELIVERED",routeId:route.delivery.id,message,receipt};}
  respond(operation,result){const pending=this.pending.get(operation.id);if(!pending)return{success:false,reason:"MESSAGE_NOT_FOUND"};const message={id:id("RMSG"),operationId:operation.id,type:"OPERATION_RESPONSE",origin:pending.message.destination,destination:pending.message.origin,service:operation.service,payload:structuredClone(result),responseTo:pending.message.id,at:new Date().toISOString()};const receipt={id:id("REC"),messageId:message.id,operationId:operation.id,senderId:message.origin,receiverId:message.destination,routeId:null,status:"RECEIVED",responseTo:pending.message.id,at:new Date().toISOString()};this.messages.push(message);this.receipts.push(receipt);this.pending.delete(operation.id);this.registry?.recordEvent?.(operation,"RESPONSE_RECEIVED",{message,receipt});return{success:true,message,receipt};}
  status(){return{messages:this.messages.length,receipts:this.receipts.length,pending:this.pending.size};} listMessages(){return this.messages.map(structuredClone);} listReceipts(){return this.receipts.map(structuredClone);}
}