import { id } from "../../../worddark/core-central/id.js";

const STATES=["GATE_ACCEPTED","COMMUNICATION_RECEIVED","ATTENDANCE_CONFIRMED","COMMERCE_OPEN","ORDER_AWAITING_PAYMENT","PAYMENT_SETTLED","SUPPLIER_ORDER_SENT","SHIPMENT_IN_TRANSIT","AFTER_SALES_OPENED","COMMERCE_CLOSED","ORDER_DELIVERED","INCIDENT_OPEN","INCIDENT_ANALYZING","INCIDENT_REQUEUED","INCIDENT_RESOLVED","PAYMENT_REFUNDED"];
export function createCommerceOperation({cityId,customerId,channel="SOCIAL",productId,amount}){if(!cityId||!customerId||!productId||amount==null)throw new Error("INVALID_COMMERCE_OPERATION");return {id:id("COM"),cityId,customerId,channel,productId,amount,status:"CREATED",history:[{status:"CREATED",at:new Date().toISOString()}],resources:{}};}
function step(op,status,data={}){if(!STATES.includes(status))throw new Error("INVALID_COMMERCE_STEP");return {...op,status,history:[...op.history,{status,...data,at:new Date().toISOString()}]};}
export function runPurchase(op,{account,supplier,shipment}){let next=step(op,"GATE_ACCEPTED");next=step(next,"COMMUNICATION_RECEIVED");next=step(next,"ATTENDANCE_CONFIRMED");next=step(next,"COMMERCE_OPEN");const order={id:id("ORD"),customerId:next.customerId,productId:next.productId,amount:next.amount,status:"AWAITING_PAYMENT"};next={...step(next,"ORDER_AWAITING_PAYMENT"),resources:{...next.resources,order:[order.id]}};const paid={...account,id:account?.id||id("ACC"),status:"PAID",amount:next.amount};order.status="PAID";next=step(next,"PAYMENT_SETTLED",{accountId:paid.id});const supplierOrder={id:id("SUP"),orderId:order.id,supplierId:supplier?.id||null,status:"SENT"};next=step(next,"SUPPLIER_ORDER_SENT",{supplierOrderId:supplierOrder.id});const ship={id:shipment?.id||id("SHP"),orderId:order.id,status:"IN_TRANSIT"};order.status="SHIPPED";next=step(next,"SHIPMENT_IN_TRANSIT",{shipmentId:ship.id});return {success:true,operation:next,order,account:paid,supplierOrder,shipment:ship};}
export function deliver({operation,order,shipment}){if(operation?.status!=="SHIPMENT_IN_TRANSIT"||order?.status!=="SHIPPED"||shipment?.status!=="IN_TRANSIT")return {success:false,reason:"DELIVERY_NOT_READY"};const next={...operation,status:"ORDER_DELIVERED",history:[...operation.history,{status:"ORDER_DELIVERED",at:new Date().toISOString()}]};return {success:true,operation:next,order:{...order,status:"DELIVERED"},shipment:{...shipment,status:"DELIVERED"}};}
export function openIncident({operation,order,type,description}){if(!operation||!type||!description)return {success:false,reason:"INVALID_INCIDENT"};const incident={id:id("INC"),operationId:operation.id,type,description,status:"OPEN",history:[{status:"OPEN",at:new Date().toISOString()}]};return {success:true,operation:step(operation,"INCIDENT_OPEN",{incidentId:incident.id}),order:order?{...order,status:"INCIDENT"}:null,incident};}
export function analyzeIncident({operation,incident}){if(incident?.status!=="OPEN")return {success:false,reason:"INCIDENT_NOT_OPEN"};const nextIncident={...incident,status:"ANALYZING",history:[...incident.history,{status:"ANALYZING",at:new Date().toISOString()}]};return {success:true,operation:step(operation,"INCIDENT_ANALYZING",{incidentId:incident.id}),incident:nextIncident};}
export function requeueIncident({operation,incident}){if(incident?.status!=="ANALYZING")return {success:false,reason:"INCIDENT_NOT_ANALYZING"};const nextIncident={...incident,status:"REQUEUED",history:[...incident.history,{status:"REQUEUED",at:new Date().toISOString()}]};return {success:true,operation:step(operation,"INCIDENT_REQUEUED",{incidentId:incident.id}),incident:nextIncident};}
export function resolveIncident({operation,incident,order,action="RESUME",note="Ocorrência resolvida."}){if(incident?.status!=="ANALYZING")return {success:false,reason:"INCIDENT_NOT_READY"};if(!["RESUME","REFUND","CANCEL"].includes(action))return {success:false,reason:"INVALID_RESOLUTION"};const resolved={...incident,status:"RESOLVED",resolution:note,history:[...incident.history,{status:"RESOLVED",note,at:new Date().toISOString()}]};let nextOrder=order;if(order&&action==="RESUME")nextOrder={...order,status:"SHIPPED"};if(order&&action==="CANCEL")nextOrder={...order,status:"CANCELLED"};if(order&&action==="REFUND")nextOrder={...order,status:"REFUNDED"};return {success:true,operation:step(operation,action==="REFUND"?"PAYMENT_REFUNDED":"INCIDENT_RESOLVED",{incidentId:incident.id}),incident:resolved,order:nextOrder};}
