import assert from "node:assert/strict";
import test from "node:test";
import {authorizeWorldAction,describeWorldBoundary,normalizePrincipal} from "./authority-boundary.mjs";
const principal=(role,zone,extra={})=>({principalId:"TEST-IDENTITY",role,zone,authenticated:true,active:true,...extra});
test("ADM Dono remains sovereign and outside internal roles",()=>{const b=describeWorldBoundary();assert.equal(b.sovereignAuthority,"ADM_DONO_EXTERNAL");assert.equal(b.sovereignAuthorityIsInternalRole,false);assert.equal(normalizePrincipal({role:"ADM-Dono",zone:"ADM",authenticated:true,active:true}).role,null);});
test("ADM operates internally but cannot grant sovereign authority or write DEV code",()=>{assert.equal(authorizeWorldAction(principal("world-admin","ADM"),"world.operate").allowed,true);assert.equal(authorizeWorldAction(principal("world-admin","ADM"),"authority.grant").reason,"SOVEREIGN_AUTHORITY_OUTSIDE_WORLD");assert.equal(authorizeWorldAction(principal("world-admin","ADM"),"dev.write").reason,"SEPARATION_OF_DUTIES");});
test("DEV can write and test but cannot administer the world",()=>{assert.equal(authorizeWorldAction(principal("developer","DEV"),"dev.write").allowed,true);assert.equal(authorizeWorldAction(principal("developer","DEV"),"dev.test").allowed,true);assert.equal(authorizeWorldAction(principal("developer","DEV"),"world.operate").reason,"DEV_CANNOT_ADMINISTER_WORLD");});
test("Public can use only published services",()=>{assert.equal(authorizeWorldAction(principal("public","PUBLIC"),"service.use").allowed,true);assert.equal(authorizeWorldAction(principal("public","PUBLIC"),"world.read").reason,"PUBLIC_INTERFACE_ONLY");});
test("Unknown, inactive and mismatched identities fail closed",()=>{assert.equal(authorizeWorldAction({}, "public.read").allowed,false);assert.equal(authorizeWorldAction(principal("developer","ADM"),"dev.write").reason,"ROLE_ZONE_MISMATCH");assert.equal(authorizeWorldAction(principal("public","PUBLIC",{active:false}),"public.read").reason,"IDENTITY_NOT_ACTIVE");});
