import { YouTubeConnector } from "../../../../core-central/social-networks.js";
const STORAGE_KEY="wd.external.connections", CLIENT_KEY="wd.youtube.clientId";
const $=s=>document.querySelector(s);
const safe=v=>String(v).replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
const providers=[
{id:"YOUTUBE",name:"YouTube",type:"SOCIAL_NETWORK",status:"READY",capabilities:["ACCOUNT_READ","CONTENT_ROUTE"]},
{id:"INSTAGRAM",name:"Instagram",type:"SOCIAL_NETWORK",status:"AUTHORIZATION_REQUIRED",capabilities:["ACCOUNT_READ","CONTENT_PUBLISH"]},
{id:"TIKTOK",name:"TikTok",type:"SOCIAL_NETWORK",status:"AUTHORIZATION_REQUIRED",capabilities:["ACCOUNT_READ","CONTENT_PUBLISH"]},
{id:"FACEBOOK",name:"Facebook",type:"SOCIAL_NETWORK",status:"AUTHORIZATION_REQUIRED",capabilities:["ACCOUNT_READ","CONTENT_PUBLISH"]}];
function connections(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||"[]")}catch{return[]}}
function save(v){localStorage.setItem(STORAGE_KEY,JSON.stringify(v))}
function render(){const items=connections();$("#providers").innerHTML=providers.map(p=>{const c=items.find(x=>x.providerId===p.id);const status=c?.status==="CONNECTED"?"CONECTADO":p.status==="READY"?"PRONTO PARA AUTORIZAÇÃO":"OAUTH PENDENTE";return '<article class="wd-entry-card"><div class="wd-card-icon">🔗</div><strong>'+safe(p.name)+'</strong><small>'+status+(c?" · "+safe(c.displayName||c.accountId):"")+'</small><small>'+safe(p.capabilities.join(" · "))+'</small></article>'}).join("");$("#connection-count").textContent=items.length+" conexão"+(items.length===1?"":"ões");$("#connection-state").textContent=items.length?items.map(x=>x.providerId+": "+(x.displayName||x.accountId)).join(" · "):"Nenhum provedor autorizado neste navegador.";$("#youtube-client-id").value=localStorage.getItem(CLIENT_KEY)||""}
async function connectYouTube(){const clientId=$("#youtube-client-id").value.trim();if(!clientId)throw new Error("YOUTUBE_CLIENT_ID_REQUIRED");localStorage.setItem(CLIENT_KEY,clientId);const note=$("#connection-note");note.textContent="Aguardando autorização do Google…";try{const result=await new YouTubeConnector({clientId}).authorize();const items=connections().filter(x=>x.providerId!=="YOUTUBE");items.push({providerId:"YOUTUBE",status:"CONNECTED",accountId:result.channel.channelId,displayName:result.channel.displayName,handle:result.channel.customUrl||"",channelUrl:result.channel.url,capabilities:["ACCOUNT_READ","CONTENT_PUBLISH"],connectedAt:new Date().toISOString()});save(items);note.textContent="YouTube conectado: "+result.channel.displayName+" · canal "+result.channel.channelId;render()}catch(error){console.error(error);note.textContent="Conexão não concluída: "+(error?.message||error)}}
$("#youtube-form").addEventListener("submit",e=>{e.preventDefault();connectYouTube()});render();