import { createChannel } from "./channel.js";
import { createCustomer } from "./customer.js";
import { createProduct } from "./product.js";
import { createCart, addCartItem } from "./cart.js";
import { createOrder } from "./order.js";
import { createSupplier } from "./supplier.js";
import { createSupplierOrder } from "./supplier-order.js";
import { createShipment } from "./shipment.js";
import { createMarketingRequest } from "./marketing-request.js";
import { createCommunication } from "./communication.js";
import { createCommerceCity } from "./city.js";
const site=createChannel({id:"WD-CH-0001",name:"Loja",type:"SITE"});
const social=createChannel({id:"WD-CH-0002",name:"Social",type:"SOCIAL",platform:"instagram"});
const customer=createCustomer({id:"WD-CUS-0001",name:"Cliente Teste"});
const product=createProduct({id:"WD-PROD-0001",name:"Produto Teste",price:99});
let cart=createCart({id:"WD-CART-0001",customerId:customer.id});
cart=addCartItem(cart,{productId:product.id,quantity:1});
const order=createOrder({id:"WD-ORD-0001",customerId:customer.id,channelId:social.id,items:cart.items,total:99});
const supplier=createSupplier({id:"WD-SUP-0001",name:"Fornecedor Teste"});
const supplierOrder=createSupplierOrder({id:"WD-SO-0001",orderId:order.id,supplierId:supplier.id,items:order.items});
const shipment=createShipment({id:"WD-SHIP-0001",orderId:order.id});
const comm=createCommunication({id:"WD-MSG-0001",channelId:site.id,customerId:customer.id});
const marketing=createMarketingRequest({id:"WD-MKT-0001",source:"COMMERCE",brief:"Criar conteúdo do produto",requestedBy:"WD-USR-0001"});
const city=createCommerceCity({id:"WD-CITY-0001"});
for (const x of [site,social,customer,product,cart,order,supplier,supplierOrder,shipment,comm,marketing,city]) if(!x) throw new Error("TEST_FAILED");
console.log("Commerce city contracts: PASS");
