import assert from "node:assert/strict";
import { DarkFactory } from "./factory.js";
import { FactoryExecutors } from "./executors.js";
const f=new DarkFactory();
const executors=new FactoryExecutors();
executors.register({id:"TEST",handler:()=>({success:true,result:"ok"})});
f.attachExecutors(executors);
const r=f.handle({id:"OP",service:"TEST",payload:{}});
assert.equal(r.success,true);
console.log("dark-factory OK");
