import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import vm from "node:vm";

const html = readFileSync(new URL("./index.html", import.meta.url), "utf8");
const scripts = [...html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/gi)];
assert.ok(scripts.length > 0, "WordDark app must contain its client script");
const source = scripts.at(-1)[1];
assert.ok(source.includes("function workbench()"), "Content workbench must be registered");
assert.ok(source.includes("data-save-review"), "Review controls must be present");
assert.ok(source.includes("function exportJobPackage(id)"), "Work packages must be exportable for manual handoff");
assert.ok(source.includes("function dispatchRequest(id)"), "Content requests must dispatch into the Dark Factory");
assert.ok(source.includes("function createLaunchMission()"), "The official launch content mission must be available");
assert.ok(source.includes("data-create-launch-mission"), "The content workbench must expose the launch mission");
assert.ok(source.includes("missionKey:'worddark-intro-v1'"), "The launch mission must have a stable key to avoid duplicates");
assert.ok(source.includes("rightsChecked:false,policyChecked:false"), "Launch content must remain unapproved until manual review");
assert.ok(source.includes("FORMATO PRINCIPAL · VÍDEO DE APRESENTAÇÃO"), "The launch package must include a main presentation script");
assert.ok(source.includes("VERSÃO CURTA · SHORT"), "The launch package must include a short-form variant");
assert.ok(source.includes("DESCRIÇÃO PARA YOUTUBE"), "The launch package must include a YouTube description");
assert.ok(source.includes("data-dispatch-request"), "Eligible requests must expose the dispatch action");
assert.ok(source.includes("requestId:r.id"), "Dispatched jobs must retain the source request ID");
assert.ok(source.includes("Solicitação de origem: '+(j.requestId||'Trabalho criado diretamente')"), "Delivery packages must preserve request provenance");
assert.ok(source.includes("linked.status=status==='Entregue'?'Concluída'"), "A delivered local job must update its source request");
assert.ok(source.includes("delete linked.linkedJobId"), "Cancelling a factory job must allow the request to be re-dispatched");
assert.ok(source.includes("data-export-job"), "Export controls must be present in the queue/editor");
assert.ok(source.includes("URL.createObjectURL(blob)"), "Export must create a downloadable package");
assert.ok(source.includes("Direitos de uso conferidos"), "Export package must include rights-review status");
assert.ok(source.includes("KEYS.contentJobs"), "Content jobs must use their own local storage key");
assert.ok(source.includes("function businessStore(kind)"), "Commercial submodules must have distinct screens");
assert.ok(source.includes("catalog:()=>businessStore('catalog')"), "Catalog route must resolve to its own module");
assert.ok(source.includes("suppliers:()=>businessStore('suppliers')"), "Supplier route must resolve to its own module");
assert.ok(source.includes("orders:()=>businessStore('orders')"), "Order route must resolve to its own module");
assert.ok(source.includes("customers:()=>businessStore('customers')"), "Customer route must resolve to its own module");
assert.ok(source.includes("function marketing()"), "Marketing must have a distinct screen");
assert.ok(source.includes("module('workbench','▧','Dark Factory'"), "Sky must link directly to the content workbench");
assert.ok(source.includes("KEYS.catalog") && source.includes("KEYS.suppliers") && source.includes("KEYS.orders") && source.includes("KEYS.customers"), "Commercial modules must persist separate record collections");
assert.ok(source.includes("data-cancel-request"), "Queued operations must support cancellation");
assert.ok(source.includes("data-delete-request"), "Queued operations must support deletion");
assert.ok(source.includes("data-cancel-job"), "Content jobs must support cancellation");
assert.ok(source.includes("data-delete-job"), "Content jobs must support deletion");
assert.ok(source.includes("item.status='Cancelada'"), "Cancellation must preserve an explicit cancelled state");
assert.ok(source.includes("requests=requests.filter(x=>x.id!==b.dataset.deleteRequest)"), "Deletion must remove the selected local operation");
assert.ok(source.includes("contentJobs=contentJobs.filter(x=>x.id!==b.dataset.deleteJob)"), "Deletion must remove the selected local content job");
assert.doesNotThrow(() => new vm.Script(source), "Inline app script must be valid JavaScript syntax");
console.log("worddark app script test: OK");
