import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import vm from "node:vm";

const html = readFileSync(new URL("./index.html", import.meta.url), "utf8");
const scripts = [...html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/gi)];
assert.ok(scripts.length > 0, "WordDark app must contain its client script");
const source = scripts.at(-1)[1];
assert.ok(source.includes("function workbench()"), "Content workbench must be registered");
assert.ok(source.includes("data-save-review"), "Review controls must be present");
assert.ok(source.includes("KEYS.contentJobs"), "Content jobs must use their own local storage key");
assert.ok(source.includes("function businessStore(kind)"), "Commercial submodules must have distinct screens");
assert.ok(source.includes("catalog:()=>businessStore('catalog')"), "Catalog route must resolve to its own module");
assert.ok(source.includes("suppliers:()=>businessStore('suppliers')"), "Supplier route must resolve to its own module");
assert.ok(source.includes("orders:()=>businessStore('orders')"), "Order route must resolve to its own module");
assert.ok(source.includes("customers:()=>businessStore('customers')"), "Customer route must resolve to its own module");
assert.ok(source.includes("function marketing()"), "Marketing must have a distinct screen");
assert.ok(source.includes("module('workbench','▧','Dark Factory'"), "Sky must link directly to the content workbench");
assert.ok(source.includes("KEYS.catalog") && source.includes("KEYS.suppliers") && source.includes("KEYS.orders") && source.includes("KEYS.customers"), "Commercial modules must persist separate record collections");
assert.ok(source.includes("data-cancel-request"), "Queued operations must support cancellation");
assert.ok(source.includes("data-delete-request"), "Queued operations must support deletion");
assert.ok(source.includes("data-cancel-job"), "Content jobs must support cancellation");
assert.ok(source.includes("data-delete-job"), "Content jobs must support deletion");
assert.ok(source.includes("item.status='Cancelada'"), "Cancellation must preserve an explicit cancelled state");
assert.ok(source.includes("requests=requests.filter(x=>x.id!==b.dataset.deleteRequest)"), "Deletion must remove the selected local operation");
assert.ok(source.includes("contentJobs=contentJobs.filter(x=>x.id!==b.dataset.deleteJob)"), "Deletion must remove the selected local content job");
assert.doesNotThrow(() => new vm.Script(source), "Inline app script must be valid JavaScript syntax");
console.log("worddark app script test: OK");
