import assert from "node:assert/strict";
import { createWordDarkWorld } from "./main.js";
import { Operation } from "./core-central/operation.js";
import { createPipeline } from "./core-central/pipeline.js";
const world=createWordDarkWorld();
let soundAttempts=0;
world.runtime.registerCapability({id:"SOUND-TEST",name:"Sound Test",owner:"DARK-FACTORY",layer:"CEU",handler:op=>{soundAttempts++;return soundAttempts===1?{success:false,reason:"AUDIO_PROBLEM"}:{success:true,result:{fixed:true,operationId:op.id}};}});
const operation=new Operation({origin:"WORDDARK-TEST-ORIGIN",service:"DARK-FACTORY",gateId:"WORLD-GATE",payload:{taskType:"IMAGE",contentId:"TEST-CONTENT"},pipeline:createPipeline(["IMAGE","SOUND-TEST","VIDEO"])});
world.runtime.request(operation);
assert.equal(operation.status,"FAILED");
assert.equal(operation.pipeline.failedModule,"SOUND-TEST");
assert.equal(operation.checkpoints.find(x=>x.module==="IMAGE")?.status,"PASSED");
assert.equal(operation.checkpoints.find(x=>x.module==="VIDEO"),undefined);
world.runtime.reenter(operation,"SOUND-TEST","AUDIO_CORRIGIDO");
assert.equal(operation.status,"COMPLETED");
assert.equal(operation.pipeline.failedModule,null);
assert.equal(operation.checkpoints.find(x=>x.module==="SOUND-TEST")?.status,"PASSED");
assert.equal(operation.checkpoints.find(x=>x.module==="VIDEO")?.status,"PASSED");
console.log("OK: pipeline modular + reentrada seletiva");
