/* Dark Factory content factory */
class ContentFactory{
constructor(o={}){this.executor=o.executor||null;this.operations=new Map();this.status="ONLINE";}
receive(r){const p=r?.payload||r||{};const op=new ContentOperation({requestId:r?.id||r?.requestId||p.requestId,action:r?.action||p.action||"CONTENT_CREATE",contentId:r?.contentId||p.contentId,contentType:r?.contentType||p.type||"MIXED",input:r?.input||p.input||null,requirements:r?.requirements||p.requirements||{},options:r?.options||p.options||{}});const v=op.validate();if(!v.valid)return{success:false,status:"REJECTED",errors:v.errors};this.operations.set(op.operationId,op);return this.plan(op);}
plan(op){op.status="PLANNED";return{success:true,status:"PLANNED",operationId:op.operationId,contentId:op.contentId,action:op.action,contentType:op.contentType,modules:this.resolveModules(op),reentry:{enabled:true,failedModuleOnly:true}};}
resolveModules(op){const m={CONTENT_CREATE:["SCRIPT","ASSET","EDIT","RENDER","VALIDATE"],CONTENT_EDIT:["INGEST","EDIT","RENDER","VALIDATE"],CONTENT_ASSEMBLE:["ASSET","TIMELINE","RENDER","VALIDATE"],CONTENT_RENDER:["RENDER","VALIDATE"],CONTENT_TRANSFORM:["INGEST","TRANSFORM","RENDER","VALIDATE"],CONTENT_VALIDATE:["VALIDATE"],ASSET_PREPARE:["INGEST","ASSET","VALIDATE"],CONTENT_PACKAGE:["VALIDATE","PACKAGE"]};return m[op.action]||["VALIDATE"];}
async execute(id){const op=this.operations.get(id);if(!op)return{success:false,status:"NOT_FOUND"};if(!this.executor?.execute)return{success:false,status:"WAITING_EXECUTOR",operationId:id};op.status="EXECUTING";const result=await this.executor.execute(op.toJSON());op.status=result?.success===false?"FAILED":"COMPLETED";return{...result,operationId:id,reentry:{enabled:true,failedModuleOnly:true}};}
reenter(id,patch={}){const op=this.operations.get(id);if(!op)return{success:false,status:"NOT_FOUND"};Object.assign(op,patch);op.status="PENDING";return this.plan(op);}
}
if(typeof window!=="undefined")window.ContentFactory=ContentFactory;if(typeof module!=="undefined"&&module.exports)module.exports=ContentFactory;