(function(root,factory){if(typeof module==="object"&&module.exports){module.exports=factory();}else{root.WordDarkImageRenderer=factory();}})(typeof self!=="undefined"?self:this,function(){
function esc(v){return String(v==null?"":v).replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));}
function dimensions(format,custom){const map={SQUARE:[1080,1080],PORTRAIT:[1080,1350],VERTICAL:[1080,1920],STORY:[1080,1920],LANDSCAPE:[1920,1080],THUMBNAIL:[1280,720],SHORT:[1080,1920],BANNER:[2560,1440]};return custom&&custom.width&&custom.height?custom:(map[String(format||"SQUARE").toUpperCase()]||map.SQUARE);}
function svg(input={}){const d=dimensions(input.format,input.dimensions),brand=esc(input.brand||"WordDark"),title=esc(input.title||input.topic||"O mundo por trás das operações."),subtitle=esc(input.subtitle||"IA · negócios · automação · produção"),w=d.width,h=d.height;const compact=w<1400;return '<svg xmlns="http://www.w3.org/2000/svg" width="'+w+'" height="'+h+'" viewBox="0 0 '+w+' '+h+'"><defs><linearGradient id="bg" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#05070d"/><stop offset=".55" stop-color="#0c1630"/><stop offset="1" stop-color="#02040a"/></linearGradient><radialGradient id="glow"><stop stop-color="#5ee7ff" stop-opacity=".5"/><stop offset="1" stop-color="#5ee7ff" stop-opacity="0"/></radialGradient></defs><rect width="100%" height="100%" fill="url(#bg)"/><circle cx="'+(w*.78)+'" cy="'+(h*.42)+'" r="'+Math.min(w,h)*.34+'" fill="url(#glow)"/><g fill="none" stroke="#65dfff" stroke-opacity=".35" stroke-width="'+Math.max(2,w/700)+'"><circle cx="'+(w*.78)+'" cy="'+(h*.42)+'" r="'+Math.min(w,h)*.25+'"/><ellipse cx="'+(w*.78)+'" cy="'+(h*.42)+'" rx="'+Math.min(w,h)*.25+'" ry="'+Math.min(w,h)*.10+'"/><ellipse cx="'+(w*.78)+'" cy="'+(h*.42)+'" rx="'+Math.min(w,h)*.10+'" ry="'+Math.min(w,h)*.25+'"/></g><circle cx="'+(w*.78)+'" cy="'+(h*.42)+'" r="'+Math.max(10,w/90)+'" fill="#fff"/><g font-family="Arial,Helvetica,sans-serif" fill="#fff"><text x="'+(w*.08)+'" y="'+(h*(compact?.34:.40))+'" font-size="'+Math.max(34,w*(compact?.055:.07))+'" font-weight="700">'+title+'</text><text x="'+(w*.08)+'" y="'+(h*(compact?.43:.50))+'" font-size="'+Math.max(20,w*(compact?.027:.035))+'" fill="#9fefff">'+subtitle+'</text><text x="'+(w*.08)+'" y="'+(h*.91)+'" font-size="'+Math.max(16,w*.018)+'" letter-spacing="5" fill="#8aa0bd">'+brand.toUpperCase()+'</text></g></svg>';}
function toBlob(input={}){
 if(typeof document==="undefined"||typeof Blob==="undefined")throw new Error("BROWSER_RENDERER_REQUIRED");
 const d=dimensions(input.format,input.dimensions),mime=String(input.mime||"image/png").toLowerCase(),canvas=document.createElement("canvas");canvas.width=d.width;canvas.height=d.height;const ctx=canvas.getContext("2d");if(!ctx)throw new Error("CANVAS_UNAVAILABLE");
 const image=new Image();const markup=svg(input);const url=URL.createObjectURL(new Blob([markup],{type:"image/svg+xml"}));
 return new Promise((resolve,reject)=>{image.onload=()=>{ctx.drawImage(image,0,0,d.width,d.height);URL.revokeObjectURL(url);canvas.toBlob(blob=>blob?resolve({blob,mime,width:d.width,height:d.height,format:input.format||"SQUARE"}):reject(new Error("IMAGE_EXPORT_FAILED")),mime,Number(input.quality||.92));};image.onerror=()=>{URL.revokeObjectURL(url);reject(new Error("SVG_LOAD_FAILED"));};image.src=url;});
}
return{dimensions,svg,toBlob};
});